kind: pipeline
name: default

# Pipeline for putting cloudformation files into S3 for nested stacks
steps:
  - name: upload-sheeta
    image: plugins/s3
    settings:
      bucket: sheeta-cfn-bucket
      region: us-east-2
      access_key:
        from_secret: sheeta_aws_key
      secret_key:
        from_secret: sheeta_aws_secret
      source: templates/**/*
      target: /${DRONE_COMMIT_SHA}/
